# Script to parse the LMDB headers and generate Julia wrappers.
#
# Usage: julia --project=res res/wrap.jl

using Clang
using Clang.Generators

using JuliaFormatter

using LMDB_jll

# Bindings whose `Cint` return is data rather than an LMDB status.
# The `@checked` post-processor leaves these alone so callers don't get
# spurious throws.
const UNCHECKED_CINT = (
    "mdb_env_get_maxkeysize",  # Maximum key size.
    "mdb_cmp",                  # Comparison result (-1, 0, or 1).
    "mdb_dcmp",                 # Duplicate-data comparison result.
    "mdb_cursor_is_db",         # Boolean result.
)
const NONNEGATIVE_CINT = ("mdb_reader_list",)

# Annotate generated `Cint` functions according to their return convention.
function postprocess!(path::AbstractString)
    src = read(path, String)
    re = r"^(?<indent>[ \t]*)function\s+(?<name>mdb_[A-Za-z0-9_]+)(?<rest>\([^\)]*\)\s*\n(?:.*\n)*?\1end\b)"m
    out = IOBuffer()
    last = 1
    for m in eachmatch(re, src)
        write(out, SubString(src, last, m.offset - 1))
        body = SubString(src, m.offset, m.offset + length(m.match) - 1)
        if m[:name] in NONNEGATIVE_CINT
            write(out, m[:indent])
            write(out, "@checked_nonnegative ")
            write(out, SubString(body, length(m[:indent]) + 1))
        elseif m[:name] ∉ UNCHECKED_CINT && occursin(r"\)::Cint\s*\n", body)
            write(out, m[:indent])
            write(out, "@checked ")
            write(out, SubString(body, length(m[:indent]) + 1))
        else
            write(out, body)
        end
        last = m.offset + length(m.match)
    end
    write(out, SubString(src, last, lastindex(src)))
    src = String(take!(out))
    src = replace(src, r"^const MDB_SIZE_MAX = SIZE_MAX$"m =>
                       "const MDB_SIZE_MAX = typemax(mdb_size_t)")
    # `Ref{MDB_val}` has pointer ABI without overlapping Base's `Ptr` conversions.
    src = replace(src, "::Ptr{MDB_val}" => "::Ref{MDB_val}")
    # Clang.Generators always emits `export $jll_pkg_name` next to its
    # `using` line; strip it so LMDB_jll stays an implementation detail.
    src = replace(src, r"^export LMDB_jll\n"m => "")
    write(path, src)
end

function main()
    cd(@__DIR__) do
        include_dir = joinpath(LMDB_jll.artifact_dir, "include") |> normpath

        args = get_default_args()
        push!(args, "-isystem$include_dir")

        options = load_options(joinpath(@__DIR__, "lmdb.toml"))

        headers = [joinpath(include_dir, "lmdb.h")]

        ctx = create_context(headers, args, options)

        build!(ctx)

        output_file = options["general"]["output_file_path"]

        postprocess!(output_file)

        output_data = read(output_file, String)
        open(output_file, "w") do io
            println(io, """# This file is automatically generated. Do not edit!
                           # To re-generate, execute res/wrap.jl""")
            println(io)
            print(io, output_data)
        end

        format_file(output_file, YASStyle())
    end

    return
end

isinteractive() || main()
